---
engines:
  # Disable engines that are not needed for this project
  - duplication:
      enabled: false
  - metrics:
      enabled: false
  - flawfinder:
      enabled: false

  # Enable appropriate engines for Python and JavaScript
  - bandit:
      enabled: true  # Python security linter
  - pylint:
      enabled: true  # Python linter
  - sonar-python:
      enabled: true  # Python static analysis
  - eslint:
      enabled: true  # JavaScript linter
  - sonarjs:
      enabled: true  # JavaScript static analysis
  - csslint:
      enabled: true  # CSS linter

files:
  # Exclude common patterns
  exclude_paths:
    - "node_modules/**"
    - ".git/**"
    - ".venv/**"
    - "__pycache__/**"
    - "*.pyc"
    - ".pytest_cache/**"
    - ".vscode/**"
    - ".github/**"
    - "dist/**"
    - "build/**"
    - "*.log"
    - ".env*"
    - "secrets.env"
    - "package-lock.json"
    - "requirements.lock"
    - "**/*.min.js"
    - "**/*.min.css"

languages:
  - python:
      engine_configs:
        - bandit:
            config_file: ".bandit"
        - pylint:
            config_file: ".pylintrc"
            max_line_length: 120
        - sonar-python:
            patterns:
              - "!**/test_*.py"
              - "!**/tests/**"
  - javascript:
      engine_configs:
        - eslint:
            config_file: ".eslintrc.json"
        - sonarjs:
            patterns:
              - "!**/node_modules/**"
              - "!test/**"
              - "!**/*.test.js"

coverage:
  disabled: false
  exclusions:
    - "**/test*/**"
    - "**/*test*.py"
    - "**/*test*.js"
