services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: assistme_db
      POSTGRES_USER: assistme_user
      POSTGRES_PASSWORD: assistme_password  # Change in production
    ports:
      - "5432:5432"
    volumes:
      - db_data_volume:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build: ./apps/api
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://assistme_user:assistme_password@db:5432/assistme_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery-worker:
    build: ./apps/api
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "-c", "print('Celery worker placeholder - service ready')"]
    depends_on:
      - redis
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data_volume: {}
