services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: assistme_db
      POSTGRES_USER: assistme_user
      POSTGRES_PASSWORD: assistme_password  # Change in production
    ports:
      - "5432:5432"
    volumes:
      - db_data_volume:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - ./secrets.env
    environment:
      DATABASE_URL: postgresql://assistme_user:assistme_password@db:5432/assistme_db
      APP_URL: http://localhost:3000
      OPENROUTER_DEFAULT_MODEL: ${OPENROUTER_DEFAULT_MODEL:-meta-llama/llama-4-scout:free}
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data_volume: {}
